# Generated by Django 6.0.3 on 2026-03-17 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='pos_left',
            field=models.IntegerField(default=50, help_text='X coordinate percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='level',
            name='pos_top',
            field=models.IntegerField(default=50, help_text='Y coordinate percentage (0-100)'),
        ),
        migrations.CreateModel(
            name='UserLevelProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_unlocked', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('stars_earned', models.IntegerField(default=0, help_text='Max 5 stars per level')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.account')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.level')),
            ],
            options={
                'unique_together': {('account', 'level')},
            },
        ),
    ]
