# Generated by Django 6.0.3 on 2026-03-17 03:39

from django.db import migrations


def seed_map_data(apps, schema_editor):
    Level = apps.get_model('core', 'Level')
    
    # Ordered list of levels exactly matching the map trail
    # ('Letter', top_percent, left_percent)
    levels_data = [
        ('M', 30, 20),
        ('I', 25, 28),
        ('O', 32, 35),
        ('B', 28, 45),
        ('E', 35, 55),
        ('U', 32, 62),
        ('T', 35, 69),
        ('K', 38, 76),
        ('L', 48, 72),
        ('Y', 52, 65),
        ('N', 50, 58),
        ('G', 53, 51),
        ('Ng', 48, 44),
        ('P', 52, 37),
        ('R', 50, 30),
        ('D', 60, 24),
        ('H', 70, 28),
        ('W', 75, 35),
    ]

    for index, (letter, top, left) in enumerate(levels_data):
        Level.objects.create(
            name=f"Letrang {letter}",
            description=f"Alamin at pag-aralan ang letrang {letter}.",
            required_stars=5,
            order=index,
            pos_top=top,
            pos_left=left
        )

def reverse_seed_data(apps, schema_editor):
    Level = apps.get_model('core', 'Level')
    Level.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_level_pos_left_level_pos_top_userlevelprogress'),
    ]

    operations = [
        migrations.RunPython(seed_map_data, reverse_seed_data),
    ]
