# Generated by Django 6.0.3 on 2026-03-17 05:51

from django.db import migrations


def update_to_horizontal_coordinates(apps, schema_editor):
    Level = apps.get_model('core', 'Level')
    
    # New horizontal trail coordinates (x, y)
    # x increases significantly to support side scrolling
    # y fluctuates subtly for an organic path
    horizontal_levels = [
        ('M', 10, 60),
        ('I', 25, 45),
        ('O', 40, 65),
        ('B', 60, 50),
        ('E', 85, 70),
        ('U', 110, 55),
        ('T', 135, 75),
        ('K', 160, 60),
        ('L', 190, 45),
        ('Y', 220, 65),
        ('N', 250, 50),
        ('G', 280, 75),
        ('Ng', 315, 60),
        ('P', 350, 45),
        ('R', 385, 65),
        ('D', 420, 50),
        ('H', 455, 70),
        ('W', 490, 55),
    ]

    for letter, x, y in horizontal_levels:
        Level.objects.filter(name=f"Letrang {letter}").update(pos_left=x, pos_top=y)

def reverse_coordinates(apps, schema_editor):
    # Optional: logic to reset to original zigzag coordinates if needed
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_map_levels'),
    ]

    operations = [
        migrations.RunPython(update_to_horizontal_coordinates, reverse_coordinates),
    ]
